export const mockData = [
   {
      "clickCharcter":"A",
      "soundName":"clap",
      "idForClickEvent":"65",
      "audioSrc":"sounds/clap.wav"
   },
   {
      "clickCharcter":"S",
      "soundName":"hihat",
      "idForClickEvent":"83",
      "audioSrc":"sounds/hihat.wav"
   },
   {
      "clickCharcter":"D",
      "soundName":"kick",
      "idForClickEvent":"68",
      "audioSrc":"sounds/kick.wav"
   },
   {
      "clickCharcter":"F",
      "soundName":"openhat",
      "idForClickEvent":"70",
      "audioSrc":"sounds/openhat.wav"
   },
   {
      "clickCharcter":"G",
      "soundName":"boom",
      "idForClickEvent":"71",
      "audioSrc":"sounds/boom.wav"
   },
   {
      "clickCharcter":"H",
      "soundName":"ride",
      "idForClickEvent":"72",
      "audioSrc":"sounds/ride.wav"
   },
   {
      "clickCharcter":"J",
      "soundName":"snare",
      "idForClickEvent":"74",
      "audioSrc":"sounds/snare.wav"
   },
   {
      "clickCharcter":"K",
      "soundName":"tom",
      "idForClickEvent":"75",
      "audioSrc":"sounds/tom.wav"
   },
   {
      "clickCharcter":"L",
      "soundName":"tink",
      "idForClickEvent":"76",
      "audioSrc":"sounds/tink.wav"
   }
]